Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "testserver"
  
  config.vm.network "forwarded_port", guest: 8080, host: 8081, auto_correct: true
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.verbose = "v"  # Включить подробный вывод
  end
end