---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create application directory
  file:
    path: "{{ app_path }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Copy application files
  copy:
    src: "{{ item }}"
    dest: "{{ app_path }}/"
    force: yes
    owner: www-data
    group: www-data
  with_fileglob:
    - "files/myapp/*"

- name: Configure Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/myapp
  notify: Restart Nginx

- name: Enable Nginx config
  file:
    src: /etc/nginx/sites-available/myapp
    dest: /etc/nginx/sites-enabled/myapp
    state: link

- name: Remove default config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart Nginx